---
- hosts: labservers
  vars:
    rule: http
  become: yes
  tasks:
  - name: include the variables from teh YAML file
    include_vars: vars/variables.yml

  - name: Include the environment file and set the variables
     import_tasks: tasks/environment.yml
        package: httpd
        service: httpd
        svc_state: started
  - name: install the firewall
      yum:
        name: "{{ firewall_pkg }}"
        state: latest
  - name: start the firewall
     service:
       name: firewalld
       state: started
       enabled: true
  - name: open the port for the {{ rule }}
     firewalld:
       service: "{{ rule }}"
       immediate: true
       permanent: true
       state: true
  - name: Create index.html file for hosting static content
    copy:
      content: "{{ ansible_fqdn }} has been customized using Ansible on the {{ansible_date_time.date }}\n"
      dest: /var/www/html/index.html
...